# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
encoding: utf-8
# Site settings
title: A.Blog
brief-intro: Do what you love & Love what you do. 
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://GaoangLiu.github.io' # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username:
github_username: GaoangLiu
email: GaoangLau@gmail.com
weibo_username: 
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer: ğŸ’¡

# comments
# ä¸‰ç§è¯„è®ºæ’ä»¶ï¼Œé€‰ä¸€ä¸ªå°±å¥½äº†
# disqus_shortname: #slipper
# gitalk:
#   enable: false
#   clientID: 0f2905fdcd849f08a1c5
#   clientSecret: c6bfab960df0d7c3af036756e7e2bcd00a44a9e6
#   repo: Gaoangliu.github.io
#   owner: Gaoangliu
#   admin: GaoangLiu
utteranc_es:
  enable: true
  repo: 'gaoangliu/gaoangliu.github.io'
  issue-term: pathname
  theme: github-light

# èµèµ
# reward:
#   enable: false
#   wechat: /assets/images/reward/wechat.png
#   alipay: /assets/images/reward/alipay.png

# statistic analysis ç»Ÿè®¡ä»£ç 
# ç™¾åº¦ç»Ÿè®¡ idï¼Œå°†ç»Ÿè®¡ä»£ç æ›¿æ¢ä¸ºè‡ªå·±çš„ç™¾åº¦ç»Ÿè®¡idï¼Œå³
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxxå­—ç¬¦ä¸²
baidu_tongji_id:
google_analytics_id:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 10

exclude: ["README.md", "LICENSE", ".post-template", ".gitignore", "start.bat"]

